/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taller1;

import javax.swing.JOptionPane;

/**
 *
 * @author Lino
 */
public class NewJFrameFormulario extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameFormulario
     */
    public NewJFrameFormulario() {
        initComponents();
        this.setTitle("Formulario");
        Limpiar();
    }

    public void Limpiar(){
        jSpinnerCantidadIngenieros.setValue(1);
        jSpinnerCantidadObreros.setValue(1);
        jSpinnerNDiasLAborados.setValue(1);
        jTextFieldValorObra.setText("0");
        jComboBoxTipoObra.setSelectedItem(1);
        jCheckBoxisPrioritaria.setSelected(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldValorObra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxTipoObra = new javax.swing.JComboBox<>();
        jSpinnerNDiasLAborados = new javax.swing.JSpinner();
        jSpinnerCantidadIngenieros = new javax.swing.JSpinner();
        jSpinnerCantidadObreros = new javax.swing.JSpinner();
        jCheckBoxisPrioritaria = new javax.swing.JCheckBox();
        jButtonCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cantidad de ingenieros");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel2.setText("Cantidad de Obreros");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 72, -1, -1));

        jLabel3.setText("Valor de materiales");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        getContentPane().add(jTextFieldValorObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 160, -1));

        jLabel5.setText("Numero de dias laborados");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setText("Tipo de obra");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jComboBoxTipoObra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "vial", "medio ambiente" }));
        jComboBoxTipoObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoObraActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTipoObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 160, -1));

        jSpinnerNDiasLAborados.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        getContentPane().add(jSpinnerNDiasLAborados, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 140, -1));

        jSpinnerCantidadIngenieros.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        getContentPane().add(jSpinnerCantidadIngenieros, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 140, -1));

        jSpinnerCantidadObreros.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        getContentPane().add(jSpinnerCantidadObreros, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 140, -1));

        jCheckBoxisPrioritaria.setText("Es prioritaria");
        jCheckBoxisPrioritaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxisPrioritariaActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxisPrioritaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 150, -1));

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        // TODO add your handling code here:
        double PagoTotal=0;
            PagoTotal+= (int)jSpinnerCantidadIngenieros.getValue()*50*
                        (int)jSpinnerNDiasLAborados.getValue();
            PagoTotal+= (int)jSpinnerCantidadObreros.getValue()*30*
                        (int)jSpinnerNDiasLAborados.getValue();
            double  ValorMaterial = Double.parseDouble(jTextFieldValorObra.getText());
            PagoTotal+= ValorMaterial;
            
            switch(jComboBoxTipoObra.getSelectedIndex()){
                case 0:
                    PagoTotal+= (PagoTotal*0.15);
                break;
                case 1:
                    PagoTotal += (PagoTotal*0.05);
                break;
            }
            
            if (jCheckBoxisPrioritaria.isSelected()){
                PagoTotal+=500;
            }
        JOptionPane.showMessageDialog(this,"El valor de la obra es de "+PagoTotal);
        Limpiar();
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jCheckBoxisPrioritariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxisPrioritariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxisPrioritariaActionPerformed

    private void jComboBoxTipoObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoObraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JCheckBox jCheckBoxisPrioritaria;
    private javax.swing.JComboBox<String> jComboBoxTipoObra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner jSpinnerCantidadIngenieros;
    private javax.swing.JSpinner jSpinnerCantidadObreros;
    private javax.swing.JSpinner jSpinnerNDiasLAborados;
    private javax.swing.JTextField jTextFieldValorObra;
    // End of variables declaration//GEN-END:variables
}
